// <auto-generated />
using System;
using CrudApplication.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudApplication.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrudApplication.Core.Entities.Persistence.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Code = "un3768",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = true,
                            Name = "Incredible Plastic Tuna"
                        },
                        new
                        {
                            Id = 74,
                            Code = "7l651p",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = true,
                            Name = "Gorgeous Fresh Bike"
                        },
                        new
                        {
                            Id = 62,
                            Code = "28669i",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = false,
                            Name = "Handcrafted Fresh Bacon"
                        },
                        new
                        {
                            Id = 16,
                            Code = "8ji8b9",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IsActive = true,
                            Name = "Unbranded Fresh Chicken"
                        },
                        new
                        {
                            Id = 59,
                            Code = "2sowq8",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = false,
                            Name = "Gorgeous Rubber Pizza"
                        },
                        new
                        {
                            Id = 58,
                            Code = "1wde53",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = true,
                            Name = "Sleek Steel Pants"
                        },
                        new
                        {
                            Id = 31,
                            Code = "ehkcgs",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IsActive = false,
                            Name = "Incredible Steel Bike"
                        },
                        new
                        {
                            Id = 81,
                            Code = "jxkmix",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IsActive = true,
                            Name = "Handcrafted Fresh Chair"
                        },
                        new
                        {
                            Id = 99,
                            Code = "qlx648",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = true,
                            Name = "Ergonomic Steel Cheese"
                        },
                        new
                        {
                            Id = 90,
                            Code = "d6s4bs",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = false,
                            Name = "Refined Plastic Fish"
                        },
                        new
                        {
                            Id = 80,
                            Code = "zx0bx4",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = false,
                            Name = "Rustic Cotton Tuna"
                        },
                        new
                        {
                            Id = 86,
                            Code = "kdkppe",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsActive = true,
                            Name = "Gorgeous Frozen Chips"
                        },
                        new
                        {
                            Id = 89,
                            Code = "69l4tn",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IsActive = false,
                            Name = "Refined Concrete Salad"
                        },
                        new
                        {
                            Id = 37,
                            Code = "m4274x",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IsActive = false,
                            Name = "Small Soft Keyboard"
                        },
                        new
                        {
                            Id = 91,
                            Code = "3g9qms",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Ergonomic Soft Cheese"
                        },
                        new
                        {
                            Id = 96,
                            Code = "odrdtg",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = true,
                            Name = "Ergonomic Wooden Sausages"
                        },
                        new
                        {
                            Id = 24,
                            Code = "wc41nc",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = true,
                            Name = "Rustic Granite Fish"
                        },
                        new
                        {
                            Id = 27,
                            Code = "ygb56v",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = false,
                            Name = "Licensed Frozen Mouse"
                        },
                        new
                        {
                            Id = 73,
                            Code = "hyy3nj",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = false,
                            Name = "Handmade Plastic Sausages"
                        },
                        new
                        {
                            Id = 46,
                            Code = "rqtdz4",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = false,
                            Name = "Generic Soft Shirt"
                        },
                        new
                        {
                            Id = 95,
                            Code = "tdj2a7",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsActive = false,
                            Name = "Rustic Plastic Chair"
                        },
                        new
                        {
                            Id = 19,
                            Code = "02j7fa",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = false,
                            Name = "Ergonomic Cotton Soap"
                        },
                        new
                        {
                            Id = 18,
                            Code = "pnfz3n",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IsActive = true,
                            Name = "Awesome Fresh Fish"
                        },
                        new
                        {
                            Id = 41,
                            Code = "ekm3gq",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = false,
                            Name = "Incredible Rubber Shirt"
                        },
                        new
                        {
                            Id = 100,
                            Code = "0y6sev",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = false,
                            Name = "Tasty Rubber Cheese"
                        },
                        new
                        {
                            Id = 1,
                            Code = "m2wbxp",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsActive = false,
                            Name = "Practical Concrete Tuna"
                        },
                        new
                        {
                            Id = 5,
                            Code = "a8q25b",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IsActive = false,
                            Name = "Intelligent Soft Bacon"
                        },
                        new
                        {
                            Id = 9,
                            Code = "yk322g",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IsActive = true,
                            Name = "Practical Fresh Towels"
                        },
                        new
                        {
                            Id = 14,
                            Code = "gcinx6",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = true,
                            Name = "Practical Soft Bike"
                        },
                        new
                        {
                            Id = 53,
                            Code = "ygvk7m",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Sleek Concrete Mouse"
                        },
                        new
                        {
                            Id = 69,
                            Code = "iwaiwv",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = true,
                            Name = "Sleek Steel Hat"
                        },
                        new
                        {
                            Id = 34,
                            Code = "38vzx7",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = false,
                            Name = "Rustic Metal Tuna"
                        },
                        new
                        {
                            Id = 11,
                            Code = "s2c6cv",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = true,
                            Name = "Handmade Plastic Hat"
                        },
                        new
                        {
                            Id = 45,
                            Code = "ikpbrg",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IsActive = false,
                            Name = "Generic Rubber Soap"
                        },
                        new
                        {
                            Id = 87,
                            Code = "iaow8o",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = false,
                            Name = "Ergonomic Soft Keyboard"
                        },
                        new
                        {
                            Id = 23,
                            Code = "57jgak",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsActive = true,
                            Name = "Small Frozen Car"
                        },
                        new
                        {
                            Id = 36,
                            Code = "bnzi38",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = true,
                            Name = "Ergonomic Cotton Ball"
                        },
                        new
                        {
                            Id = 77,
                            Code = "uarxpi",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IsActive = true,
                            Name = "Practical Plastic Chair"
                        },
                        new
                        {
                            Id = 71,
                            Code = "5rxw0x",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = false,
                            Name = "Refined Granite Cheese"
                        },
                        new
                        {
                            Id = 54,
                            Code = "h4m5xj",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = true,
                            Name = "Handmade Plastic Chair"
                        },
                        new
                        {
                            Id = 35,
                            Code = "a7rkip",
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            IsActive = true,
                            Name = "Intelligent Soft Car"
                        },
                        new
                        {
                            Id = 48,
                            Code = "qo49js",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IsActive = true,
                            Name = "Licensed Fresh Shirt"
                        },
                        new
                        {
                            Id = 64,
                            Code = "dosc0j",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = true,
                            Name = "Generic Granite Shirt"
                        },
                        new
                        {
                            Id = 75,
                            Code = "n4xfjk",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = true,
                            Name = "Unbranded Rubber Computer"
                        },
                        new
                        {
                            Id = 82,
                            Code = "d3bg9k",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = false,
                            Name = "Refined Metal Tuna"
                        },
                        new
                        {
                            Id = 78,
                            Code = "o2mj8f",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = true,
                            Name = "Generic Steel Shoes"
                        },
                        new
                        {
                            Id = 93,
                            Code = "6zt6z8",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = true,
                            Name = "Awesome Rubber Fish"
                        },
                        new
                        {
                            Id = 76,
                            Code = "a6gy44",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = false,
                            Name = "Refined Cotton Hat"
                        },
                        new
                        {
                            Id = 50,
                            Code = "629aai",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = true,
                            Name = "Practical Soft Tuna"
                        },
                        new
                        {
                            Id = 32,
                            Code = "un9i95",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = false,
                            Name = "Tasty Soft Mouse"
                        },
                        new
                        {
                            Id = 84,
                            Code = "2hs7ax",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IsActive = false,
                            Name = "Ergonomic Wooden Bike"
                        },
                        new
                        {
                            Id = 97,
                            Code = "ee5bgi",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = false,
                            Name = "Incredible Soft Soap"
                        },
                        new
                        {
                            Id = 65,
                            Code = "s9ec88",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = false,
                            Name = "Ergonomic Concrete Salad"
                        },
                        new
                        {
                            Id = 7,
                            Code = "1ehdcr",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = false,
                            Name = "Handcrafted Frozen Sausages"
                        },
                        new
                        {
                            Id = 29,
                            Code = "ebirm6",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IsActive = false,
                            Name = "Handcrafted Rubber Soap"
                        },
                        new
                        {
                            Id = 26,
                            Code = "yk6vda",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = true,
                            Name = "Small Wooden Bike"
                        },
                        new
                        {
                            Id = 2,
                            Code = "bwd3cm",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IsActive = true,
                            Name = "Unbranded Plastic Shirt"
                        },
                        new
                        {
                            Id = 44,
                            Code = "2rwpm2",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Incredible Metal Car"
                        },
                        new
                        {
                            Id = 72,
                            Code = "rjzqof",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = true,
                            Name = "Intelligent Metal Pizza"
                        },
                        new
                        {
                            Id = 30,
                            Code = "47vbvn",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IsActive = false,
                            Name = "Handcrafted Fresh Chair"
                        },
                        new
                        {
                            Id = 83,
                            Code = "w06dv2",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = true,
                            Name = "Fantastic Frozen Shirt"
                        },
                        new
                        {
                            Id = 60,
                            Code = "dovxde",
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            IsActive = false,
                            Name = "Sleek Cotton Sausages"
                        },
                        new
                        {
                            Id = 33,
                            Code = "oxzsm2",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IsActive = true,
                            Name = "Rustic Metal Gloves"
                        },
                        new
                        {
                            Id = 85,
                            Code = "slspab",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Sleek Wooden Salad"
                        },
                        new
                        {
                            Id = 39,
                            Code = "m84kd1",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = false,
                            Name = "Gorgeous Steel Soap"
                        },
                        new
                        {
                            Id = 6,
                            Code = "4stfcl",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IsActive = true,
                            Name = "Handmade Concrete Shirt"
                        },
                        new
                        {
                            Id = 43,
                            Code = "he3xjx",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = true,
                            Name = "Handmade Metal Bacon"
                        },
                        new
                        {
                            Id = 42,
                            Code = "imdqdq",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = true,
                            Name = "Ergonomic Steel Shirt"
                        },
                        new
                        {
                            Id = 61,
                            Code = "0jb34x",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsActive = false,
                            Name = "Incredible Plastic Soap"
                        },
                        new
                        {
                            Id = 79,
                            Code = "w1s3q3",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = true,
                            Name = "Unbranded Soft Ball"
                        },
                        new
                        {
                            Id = 38,
                            Code = "yqfyo7",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = true,
                            Name = "Small Fresh Table"
                        },
                        new
                        {
                            Id = 66,
                            Code = "qh3kav",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Licensed Cotton Keyboard"
                        },
                        new
                        {
                            Id = 13,
                            Code = "f95qui",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = true,
                            Name = "Practical Metal Towels"
                        },
                        new
                        {
                            Id = 28,
                            Code = "kuz7sd",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = false,
                            Name = "Intelligent Cotton Towels"
                        },
                        new
                        {
                            Id = 47,
                            Code = "ojogc7",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = true,
                            Name = "Fantastic Plastic Chips"
                        },
                        new
                        {
                            Id = 52,
                            Code = "cp3qdf",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = false,
                            Name = "Awesome Concrete Tuna"
                        },
                        new
                        {
                            Id = 40,
                            Code = "7u773l",
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            IsActive = true,
                            Name = "Small Wooden Table"
                        },
                        new
                        {
                            Id = 21,
                            Code = "xehe9p",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = true,
                            Name = "Practical Fresh Table"
                        },
                        new
                        {
                            Id = 10,
                            Code = "cyuwot",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = true,
                            Name = "Generic Cotton Bike"
                        },
                        new
                        {
                            Id = 67,
                            Code = "wdfvb5",
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            IsActive = true,
                            Name = "Refined Frozen Fish"
                        },
                        new
                        {
                            Id = 55,
                            Code = "cxkwah",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = true,
                            Name = "Tasty Cotton Pizza"
                        },
                        new
                        {
                            Id = 49,
                            Code = "9epp33",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = true,
                            Name = "Generic Plastic Shoes"
                        },
                        new
                        {
                            Id = 63,
                            Code = "bts8wq",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = false,
                            Name = "Refined Steel Tuna"
                        },
                        new
                        {
                            Id = 15,
                            Code = "h7ggoh",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsActive = false,
                            Name = "Awesome Cotton Computer"
                        },
                        new
                        {
                            Id = 57,
                            Code = "4vjtjv",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = true,
                            Name = "Awesome Concrete Hat"
                        },
                        new
                        {
                            Id = 22,
                            Code = "aoz5li",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = true,
                            Name = "Small Metal Chips"
                        },
                        new
                        {
                            Id = 51,
                            Code = "xiz1x7",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IsActive = true,
                            Name = "Handmade Soft Hat"
                        },
                        new
                        {
                            Id = 12,
                            Code = "0hzhkq",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = true,
                            Name = "Gorgeous Concrete Chips"
                        },
                        new
                        {
                            Id = 92,
                            Code = "jki98z",
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            IsActive = false,
                            Name = "Intelligent Plastic Soap"
                        },
                        new
                        {
                            Id = 98,
                            Code = "0cc5xm",
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            IsActive = true,
                            Name = "Tasty Metal Gloves"
                        },
                        new
                        {
                            Id = 56,
                            Code = "3ffyjr",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = true,
                            Name = "Licensed Steel Fish"
                        },
                        new
                        {
                            Id = 20,
                            Code = "t5mire",
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            IsActive = false,
                            Name = "Gorgeous Concrete Chicken"
                        },
                        new
                        {
                            Id = 68,
                            Code = "kbuxwi",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = false,
                            Name = "Gorgeous Granite Table"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ifrw7n",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = true,
                            Name = "Refined Steel Chair"
                        },
                        new
                        {
                            Id = 70,
                            Code = "1pyjri",
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            IsActive = false,
                            Name = "Fantastic Soft Shirt"
                        },
                        new
                        {
                            Id = 4,
                            Code = "h2rz0w",
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            IsActive = true,
                            Name = "Tasty Cotton Soap"
                        },
                        new
                        {
                            Id = 88,
                            Code = "jmh7wv",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = true,
                            Name = "Practical Metal Shirt"
                        },
                        new
                        {
                            Id = 25,
                            Code = "inpvlk",
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            IsActive = false,
                            Name = "Sleek Granite Keyboard"
                        },
                        new
                        {
                            Id = 94,
                            Code = "nj8odf",
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            IsActive = false,
                            Name = "Intelligent Frozen Shirt"
                        },
                        new
                        {
                            Id = 17,
                            Code = "faqyb5",
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            IsActive = false,
                            Name = "Tasty Wooden Soap"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
